opcode 5XY0
s-society/chip-8 pull request #63
Opened 2016-10-20 10:46 UTC by megastorm7

2016-10-20 10:48 UTC, alarsyo requested changes
Classe ton opcode alphabétiquement stp 😃

2016-10-21 14:39 UTC, ilnoumri approved these changes

2016-10-23 11:32 UTC, alarsyo approved these changes
Looks good to me

2016-10-23 11:32 UTC, alarsyo commented
@nagan0ri please look et approuve qu'on puisse merge celle ci :P

2016-10-24 14:24 UTC, ghost approved these changes

2016-10-24 16:06 UTC, merged