Opcode 8XYK
s-society/chip-8 pull request #64
Opened 2016-10-20 10:47 UTC by ilnoumri

#17 #18 #19 #21 #23 #25 #27 #30 #32

2016-10-23 11:30 UTC, alarsyo commented
Je regarde celle ci dès que j'ai un PC sous la main, elle est un peu longue sinon xD

2016-10-24 14:06 UTC, megastorm7 commented on Chip8/Chip8/OpCodes.fs
> +let instruction_8XY5 opcode = let X = int (opcode &&& 0x0F00us >>> 8) in
/!\

2016-10-24 14:20 UTC, alarsyo requested changes

2016-10-24 14:20 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
> +                              if (uint16 X + uint16 Y > 0xFFus) then chip8.Vx.[0xF] <- 1uy else chip8.Vx.[0xF] <- 0uy
à changer, t'additionne les indices là.... x))

2016-10-24 14:20 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
> +                              if (chip8.Vx.[X] > chip8.Vx.[Y]) then chip8.Vx.[0xF] <- 1uy else chip8.Vx.[0xF] <- 0uy
ta comparaison tu la fais après avoir assigné une nouvelle valeur à `Vx.[X]`

2016-10-24 14:20 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
> +                              chip8.Vx.[X] <- chip8.Vx.[Y] >>> 1
`Vx.[Y]` est pas utilisé là

2016-10-24 14:20 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
> +let instruction_8XY7 opcode = let X = int (opcode &&& 0x0F00us >>> 8) in
Celui là c'est un copié collé du 8XY5, t'as pas modifié ce qu'il fallait

2016-10-24 14:21 UTC, ghost approved these changes

2016-10-24 14:24 UTC, ghost approved these changes

2016-10-24 14:45 UTC, alarsyo submitted a review, later dismissed

2016-10-25 15:16 UTC, RitoFan reviewed
짜증

2016-10-25 15:27 UTC, alarsyo approved these changes
Utsukushii

2016-10-25 15:42 UTC, merged