opcode delay timer
s-society/chip-8 pull request #70
Opened 2016-10-24 15:14 UTC by megastorm7

2016-10-24 15:18 UTC, ilnoumri approved these changes

2016-10-24 16:15 UTC, alarsyo requested changes

2016-10-24 16:15 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
> +// FX15 - Affecte VX au timer principal DT
Une ligne d'espace entre cette fonction et celle d'avant please :stuck_out_tongue:

2016-10-25 14:36 UTC, alarsyo approved these changes

2016-10-25 14:54 UTC, ghost approved these changes
Seems good to me

2016-10-25 14:58 UTC, merged