opcode FX07
s-society/chip-8 pull request #71
Opened 2016-10-24 15:42 UTC by megastorm7

2016-10-24 15:52 UTC, ilnoumri approved these changes

2016-10-24 16:17 UTC, alarsyo requested changes

2016-10-24 16:17 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
>  // FX1E - Affecte VX + I à I
Un espace ici please :stuck_out_tongue:

2016-10-24 16:17 UTC, alarsyo commented on Chip8/Chip8/OpCodes.fs
> +// FX07 - VX -> DelayTimer
Un autre espace ici please :stuck_out_tongue:

2016-10-25 14:45 UTC, alarsyo approved these changes

2016-10-25 14:56 UTC, ghost approved these changes
Okus Dokus

2016-10-25 15:04 UTC, merged